server:
  port: 8081

spring:
  datasource:
    url:
    username:
    password:

mybatis-plus:
  mapper-locations: classpath:com/zero/iweiojbackend/mapper/**/*.xml

  cos:
    secretId:
    secretKey:
    reginName:
    bucketName:
    url:
    prefix: