server:
  port: 8081

spring:
  datasource:
    url:
    username:
    password:
  redis:
    host:
    database:

mybatis-plus:
  mapper-locations: classpath:com/zero/iweiojbackend/mapper/**/*.xml

cos:
  secretId:
  secretKey:
  reginName:
  bucketName:
  url:
  prefix:

codesandbox:
  type: example

judge:
  url: http://localhost:8082/sandbox/judge